server:
  error:
    include-message: always
spring:
  diff-sync:
    path: sync
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;MODE=MYSQL;
    username: SA
    password:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true


